services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: edupredict_api
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - prometheus

    networks:
      - app_net

  prefect_server:
    image: prefecthq/prefect:2-latest
    container_name: prefect_server
    entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - app_net
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: edupredict_ui
    env_file: .env
    ports:
      - "${STREAMLIT_PORT}:${STREAMLIT_PORT}" 
    depends_on:
      - backend
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: edupredict_prometheus
    volumes:
      - ./backend/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - app_net

  grafana:
    image: grafana/grafana:latest
    container_name: edupredict_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app_net

networks:
  app_net:
    driver: bridge