name: Predict MLOps
on: 
  push: 
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: üîî Discord notification - Begin Training & Audit
      if: always()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.CICD_PIPELINE_DISCORD }}
        status: ${{ job.status}}
        title: "üöÄ Starting Training & Audit"
        description: "Training and audit for commit : **${{ github.event.head_commit.message }}**"
        username: "CI/CD Bot"
    - name: ‚¨áÔ∏è Code checkout
      uses: actions/checkout@v4

    - name: üêç Configuration Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: üì¶ Dependencies setup
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Training & Audit
      env:
          MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
          PYTHON_PATH: "."
      run: |
        python core/pipeline_core/tuning.py
    - name: Discord Notification on Success
      if: success()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.CICD_PIPELINE_DISCORD }}
        status: ${{ job.status}}
        title: "‚úÖ Training & Audit success"
        description: "Training and audit for commit : **${{ github.event.head_commit.message }}**"
        username: "CI/CD Bot"

    - name: Discord Notification on Failure
      if: failure()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.CICD_PIPELINE_DISCORD }}
        status: ${{ job.status}}
        description: "‚ùå Deployment Failed: Model performance too low! for commit : **${{ github.event.head_commit.message }}**"
        username: "CI/CD Bot"